# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/ip/Blue_Mult/Blue_Mult.xci
# IP: The module: 'Blue_Mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/ip/Blue_Mult/Blue_Mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Blue_Mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/ip/Blue_Mult/Blue_Mult.xci
# IP: The module: 'Blue_Mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/ip/Blue_Mult/Blue_Mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Blue_Mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
