# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg484-2L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/COE File/SRAM_COE_LENA_RGB.coe}}
add_files -quiet {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/RAM_A_synth_1/RAM_A.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/RAM_A_synth_1/RAM_A.dcp}}]
add_files -quiet {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/RAM_B_synth_1/RAM_B.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/RAM_B_synth_1/RAM_B.dcp}}]
add_files -quiet {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Red_Mult_synth_1/Red_Mult.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Red_Mult_synth_1/Red_Mult.dcp}}]
add_files -quiet {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Green_Mult_synth_1/Green_Mult.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Green_Mult_synth_1/Green_Mult.dcp}}]
add_files -quiet {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Blue_Mult_synth_1/Blue_Mult.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Blue_Mult_synth_1/Blue_Mult.dcp}}]
add_files -quiet {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Adder_synth_1/Adder.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Adder_synth_1/Adder.dcp}}]
add_files -quiet {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Address_Counter_synth_1/Address_Counter.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Address_Counter_synth_1/Address_Counter.dcp}}]
add_files -quiet {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Adder2_synth_1/Adder2.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.runs/Adder2_synth_1/Adder2.dcp}}]
read_vhdl -library xil_defaultlib {
  {C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/new/Reg_16bit.vhd}
  {C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/new/FSM.vhd}
  {C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/new/Converter.vhd}
  {C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/new/Complete_Chip.vhd}
}
read_xdc {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/constrs_1/new/Const1.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/constrs_1/new/Const1.xdc}}]

synth_design -top Complete_Chip -part xc7a100tfgg484-2L
write_checkpoint -noxdef Complete_Chip.dcp
catch { report_utilization -file Complete_Chip_utilization_synth.rpt -pb Complete_Chip_utilization_synth.pb }
