# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/ip/Address_Counter/Address_Counter.xci
# IP: The module: 'Address_Counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/ip/Address_Counter/Address_Counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Address_Counter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/ip/Address_Counter/Address_Counter.xci
# IP: The module: 'Address_Counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Arsany A. Temothaws/Desktop/FPGA Project pipeline/FPGA Project pipeline/FPGA Project pipeline.srcs/sources_1/ip/Address_Counter/Address_Counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Address_Counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
